export const GET_MEDICINES = "GET_MEDICINES";
export const ITEM_WAS_SET = "ITEM_WAS_SET";
export const CHANGE_MODAL_STATUS = "CHANGE_MODAL_STATUS";
export const ITEM_WAS_DELETED = "ITEM_WAS_DELETED";
export const ITEM_WAS_UPDATED = "ITEM_WAS_UPDATED";
